name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ecommercezy_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo, pdo_mysql
        ini-values: post_max_size=256M, upload_max_filesize=256M, max_execution_time=300
        coverage: none

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env Example
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Database Migration
      run: |
        php artisan migrate --force

    - name: Run Laravel Tests
      run: |
        php artisan test
